### PR TITLE
Feature/initial liberty packages

### PR DESCRIPTION
**Pull request by hgpestana**
## What was done
Implemented the necessary operations for interacting with the Liberty servers. 

As of now, it supports:
 - Deploying artifacts to a Liberty server 
 - Undeploying artifacts from a Liberty server
 - Starting, stopping and restarting artifacts in a Liberty server
 - Listing existing artifacts from a given package in a Liberty server

## Closes
Closes PTDOPFU1171648I-417

### CODE REVIEW

**Comment by crisgoncalves** [comment]
Hey @hgpestana.

As discussed, we can implement a Builder to easy the construction of the `DeliverService`'s object.

Thanks.

**Comment by hgpestana** [comment]
> Hey @hgpestana.
> 
> As discussed, we can implement a Builder to easy the construction of the `DeliverService`'s object.
> 
> Thanks.

Hey @crisgoncalves 

Resolved at 5cbe9d8. Please check it out again

**Comment by hgpestana** [comment]
@crisgoncalves as discussed, a new custom strategy was implemented in order to support creating custom config files for each deployment, allowing us better control over the said artifact deployments. Please review the new code changes.

Thanks

**Review by crisgoncalves — APPROVED** [review]
Performed the following set of tests successfully:
* Install artifact
* Start Artifact
* Stop Artifact
* Uninstall artifact

`DeployService` instantiation through provided builders seems ok, so everything's good to go!

**Pull request merged**
